version: "2"
services:
  airea:
    restart: unless-stopped
    image: "ghcr.io/natant-network/airea:main"
    ports:
    #IMPORTANT: DO NOT CHANGE THE 6969 PART ONLY CHANGE THE <your port here> PART REMOVING THE <> AROUND IT
      - <your port here>:8080
