name: "Gitea SYNC"
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: varunsridharan/action-gitea-mirror@1.1
        name: "Sync"
        with:
          # Github Username
          gh_username: ${{ secrets.GH_USERNAME }}
          # Github Personal Access Token
          gh_accesstoken: ${{ secrets.GH_TOKEN }}
          # Gitea Mirror Host URL
          gh_username: ${{ secrets.GH_USERNAME }}
          gh_accesstoken: ${{ secrets.GH_TOKEN }}
          gitea_host: ${{ secrets.GITEA_HOST }}
          gitea_username: ${{ secrets.GITEA_USERNAME }}
          gitea_accesstoken: ${{ secrets.GITEA_TOKEN }}
          gitea_gist_prefix: "gist"
          gitea_gist_surfix: ""
          gistsSource: true
          gistsStared: true
          repositoryStared: true
          repositorySource: true
          repositoryForked: true
